//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlphaLog
    {
        public long LogId { get; set; }
        public System.TimeSpan CurrentTime { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public string UserName { get; set; }
        public string LogType { get; set; }
        public string LogEntry { get; set; }
    }
}
