//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileSyncLoggingEntities : DbContext
    {
        public FileSyncLoggingEntities()
            : base("name=FileSyncLoggingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlphaLog> AlphaLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<FileOperation> FileOperations { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<InteractionType> InteractionTypes { get; set; }
        public virtual DbSet<LogType> LogTypes { get; set; }
    }
}
