//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public System.TimeSpan LogTime { get; set; }
        public System.DateTime LogDate { get; set; }
        public int LogTypeId { get; set; }
        public int InteractionTypeId { get; set; }
        public string Domain { get; set; }
        public string UserName { get; set; }
        public string PCName { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileOperationId { get; set; }
        public string ErrorMsg { get; set; }
        public virtual FileOperation FileOperation { get; set; }
        public virtual InteractionType InteractionType { get; set; }
        public virtual LogType LogType { get; set; }
    }
}
